# syntax=docker/dockerfile:1.4
FROM alpine:3.19

RUN apk add git python3 pipx

WORKDIR /app

COPY requirements.txt /app
RUN --mount=type=cache,target=/root/.cache/pip \
    cat requirements.txt | xargs -d\\n -n1 pipx install

COPY . /app
CMD ["waitress-serve", "--threads=6", "--port=8000", "--call", "app:create_app"]
