"""New

Revision ID: 17d1945fa422
Revises: 
Create Date: 2023-09-26 09:15:03.337248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d1945fa422'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('password_nas', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('alias', sa.String(length=20), nullable=True),
    sa.Column('_groups', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('admin_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('n_date', sa.Date(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('proc', sa.String(length=15), nullable=True),
    sa.Column('permanent_link', sa.String(length=150), nullable=True),
    sa.Column('reg', sa.String(length=15), nullable=True),
    sa.Column('_groups', sa.String(length=15), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.Column('received_by', sa.String(length=150), nullable=True),
    sa.Column('read_by', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.Column('permanent_link', sa.String(length=150), nullable=True),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('note_receiver',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], )
    )
    op.create_table('note_ref',
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], ),
    sa.ForeignKeyConstraint(['ref_id'], ['note.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_ref')
    op.drop_table('note_receiver')
    op.drop_table('file')
    op.drop_table('note')
    op.drop_table('user')
    # ### end Alembic commands ###
