"""User date

Revision ID: 18716431d1e3
Revises: fd58081609f3
Create Date: 2023-09-28 10:32:29.188455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18716431d1e3'
down_revision = 'fd58081609f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
