"""Local path users

Revision ID: 290afb50c526
Revises: fda0063d6510
Create Date: 2023-10-21 12:02:51.573105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '290afb50c526'
down_revision = 'fda0063d6510'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('local_path', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('local_path')

    # ### end Alembic commands ###
