"""New

Revision ID: 43e95a778f4b
Revises: 17d1945fa422
Create Date: 2023-09-26 09:49:45.975167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e95a778f4b'
down_revision = '17d1945fa422'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('n_groups', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))
        batch_op.drop_column('_groups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_groups', sa.VARCHAR(length=15), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('n_groups')

    # ### end Alembic commands ###
