"""New

Revision ID: fd58081609f3
Revises: 43e95a778f4b
Create Date: 2023-09-26 10:10:15.610764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd58081609f3'
down_revision = '43e95a778f4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('u_groups', sa.String(length=200), nullable=True))
        batch_op.drop_column('_groups')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_groups', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('u_groups')

    # ### end Alembic commands ###
